# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cc9fa6d9c53e9c80a4d75686b5bb3134a97745d2f63c4f2c1838a7db366aa8edfad5217443c01a5b7684294b3ffe90d7555a68a1172e2c489c8d93d9fb112d9

test:
  secret_key_base: 2e8831d09b63c325c5ab6a7dd19aaef3c3c12cbc18615e845fda9bc1277be1d8e03495c356a8bc729d408249e660b3444e7ff2a45ebae184b60fcb83e6d6b1a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
